# Generated by Django 3.1.2 on 2020-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Cost',
            field=models.CharField(help_text='Enter a cost of the food', max_length=13, unique=True, verbose_name='Cost'),
        ),
    ]
