# Generated by Django 3.1.2 on 2020-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201210_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the drink', max_length=1000)),
                ('Cost', models.CharField(help_text='Enter a cost of the drink', max_length=13, unique=True, verbose_name='Cost')),
                ('Type', models.ManyToManyField(help_text='Select a type for this drink', to='catalog.Type')),
            ],
        ),
    ]
