# Generated by Django 3.1.2 on 2020-12-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201211_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='Type',
        ),
        migrations.AddField(
            model_name='drink',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type'),
        ),
        migrations.AlterField(
            model_name='tableinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Table availability', max_length=1),
        ),
    ]
