# Generated by Django 3.1.2 on 2020-12-11 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_auto_20201211_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set table as returned'),)},
        ),
        migrations.AddField(
            model_name='tableinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tableinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
